version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      PROJECT_ID: ${PROJECT_ID}
      BUCKET_NAME: ${BUCKET_NAME}
      POLYGON_API_KEY: ${POLYGON_API_KEY}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - ../data:/home/src/data
      # specify the path to your GCP credentials file
      - ~/.config/gcp/my-creds.json:/home/src/personal-gcp.json
    restart: on-failure
